### ISSUE TITLE
Losing verifiable context with inner functions

### ISSUE THREAD

**Issue by delasteve** [florinn/typemoq#51]
First, awesome library! Thank you.

I have a class that I need to return a function. It will call methods inside the same class. It looks something like the following...

```ts
class Foo {
  register(): () => void {
    return () => {
      this.canExecute();
    };
  }

  canExecute(): void {
    console.log('>> in canExecute <<');
  }
}
```

I want to verify that `canExecute` is being called, and it is. The problem lies in the fact that `TypeMoq` doesn't see it being called. I have the following test...

```ts
describe('Foo', () => {
  it('when register() invoked calls canExecute()', () => {
    let mock: IMock<Foo> = Mock.ofType(Foo);
    mock.callBase = true;
    const registerInnerFunction = mock.object.register();

    registerInnerFunction();

    mock.verify(x => x.canExecute(), Times.once());
  });
});
```

And get the following output...

```
  Foo
>> in canExecute <<
    1) when register() invoked calls canExecute()


  0 passing (30ms)
  1 failing

  1) Foo when register() invoked calls canExecute():
     MockException - invocation count verification failed (expected invocation of Foo.canExecute() 1 times, invoked 0 times
      at MockException.Exception [as constructor] (node_modules/typemoq/dist/Error/Error/Error/Exception.ts:3:9)
      at new MockException (node_modules/typemoq/dist/Error/Error/Error/MockException.ts:20:9)
      at InterceptorExecute.throwVerifyCallCountException (node_modules/typemoq/dist/InterceptorExecute.ts:55:17)
      at InterceptorExecute.verifyCallCount (node_modules/typemoq/dist/InterceptorExecute.ts:51:18)
      at StaticMock.verify (node_modules/typemoq/dist/StaticMock.ts:66:31)
      at Context.it (src/foo.spec.ts:87:10)
```

Thanks again for the great work!

**Comment by delasteve** [comment]
After a bit more testing, it looks like it's an issue with `callBase`.

I tried the following, removing the inner function, and get the same output when running the test.

```ts
class Foo {
  register(): void {
    this.canExecute();
  }

  canExecute(): void {
    console.log('>> in canExecute <<');
  }
}

describe.only('Foo', () => {
  it('when register() invoked calls canExecute()', () => {
    let mock: IMock<Foo> = Mock.ofType(Foo);
    mock.callBase = true;

    mock.object.register();

    mock.verify(x => x.canExecute(), Times.once());
  });
});
```

**Comment by florinn** [comment]
Thanks, good to hear the library is useful to you.

I've added support for your testing scenario.
Please install the dev version and let me know if you run into problems.

**Comment by delasteve** [comment]
It works! Thanks for the quick turnaround!

**Comment by delasteve** [comment]
Actually, I noticed with your test, it should be calling `canExecute` twice. I ran the tests locally with the `console.log` commented out and got the following.

```   
✓ should not call the underlying object of a mock created from a function type when callBase is false
Foo.canExecute()
Foo.canExecute()
```

```ts
it("should verify any inner calls inside a method call when callBase is true", () => {

    let mock: TypeMoq.IMock<TypeMoqTests.Foo> = Mock.ofType(TypeMoqTests.Foo);
    mock.callBase = true;

    mock.object.register();
    mock.object.registerLambda();

    // this should be Times.exactly(2)?
    mock.verify(x => x.canExecute(), Times.once());
});
```

**Comment by florinn** [comment]
To be able to intercept the inner calls, typemoq needs to override "this", which is possible for regular functions but not for lambda ones.

That extra call you've noticed it is meant to show that inner calls inside a lambda function cannot be verified.
