### ISSUE TITLE
Getting Exception thrown the second time I run my tests 

### ISSUE THREAD

**Issue by CodingMadeEasy** [florinn/typemoq#72]
This is the error message I'm getting:

```
Error: function () {
                var args = [];
                for (var _i = 0; _i < arguments.length; _i++) {
                    args[_i] = arguments[_i];
                }
                _this._interceptor.removeInvocation(invocation);
                var method = new MethodInfo(target, p);
                var methodInvocation = new MethodInvocation(target, method, args, ProxyType.DYNAMIC);
                _this._interceptor.intercept(methodInvocation);
                return methodInvocation.returnValue;
            }: undefined

at Function.LoadShader (src/client/util/shaderUtil.ts:37:19)
at Function.Load (src/client/util/shaderUtil.ts:13:46)
at Context.it (tests/client/util/shaderUtil.ts:26:8)
```

And here is my test code.

```
let mock: TypeMoq.IMock<WebGL2RenderingContext> = canvasHelper.WebGL2ContextMock;
sinon.spy(mock.object.linkProgram);
sinon.spy(mock.object.deleteShader);
sinon.spy(ShaderUtil.Load);

mock.setup(x => x.linkProgram).verifiable(TypeMoq.Times.once(), TypeMoq.ExpectedCallType.InSequence);
mock.setup(x => x.deleteShader).verifiable(TypeMoq.Times.atLeastOnce(), TypeMoq.ExpectedCallType.InSequence);

ShaderUtil.Load(mock.object, '#version 330 es', '#version 330 es');

mock.verifyAll();
```

Lastly here is my ShaderUtil class: 

```
export class ShaderUtil
{
// #region Public Methods.
    /**
     * Loads the shader file.
     * @param {WebGL2RenderingContext} gl - The webgl context.
     * @param {string} vertexShaderText - The vertex shader file contents.
     * @param {number} fragmentShaderText - The fragment shader file contents.
     */
    public static Load(gl: WebGL2RenderingContext, vertexShaderText: string, fragmentShaderText: string): WebGLProgram
    {
        let shaderProgram: WebGLProgram = gl.createProgram();
        let vertexShader: WebGLShader = this.LoadShader(gl, vertexShaderText, gl.VERTEX_SHADER);
        let fragmentShader: WebGLShader = this.LoadShader(gl, fragmentShaderText, gl.FRAGMENT_SHADER);

        gl.attachShader(shaderProgram, vertexShader);
        gl.attachShader(shaderProgram, fragmentShader);
        gl.linkProgram(shaderProgram);

        gl.deleteShader(vertexShader);
        gl.deleteShader(fragmentShader);

        return shaderProgram;
    }
// #endregion

// #region Private Methods.
    /** Compiles the shader text and returns the shader. */
    private static LoadShader(gl: WebGL2RenderingContext, shaderText: string, shaderType: number): WebGLShader
    {
        let shader: WebGLShader = gl.createShader(shaderType);
        gl.shaderSource(shader, shaderText);
        gl.compileShader(shader);

        if (!gl.getShaderParameter(shader, gl.COMPILE_STATUS))
        {
            throw new Error(`${shaderType}: ${gl.getShaderInfoLog(shader)}`);
        }

        return shader;
    }
// #endregion
}
```

It's extremely weird. I'm using mocha-webpack and the first time I run the test, it's green which leads me to believe that everything is fine but if I re-save the file without adding anything, I get the error message that I posted above. 

Not sure if it's a problem with TypeMoq or Mocha-Webpack but it's extremely weird and frustrating.

**Comment by CodingMadeEasy** [comment]
You can close this. I've figured out how to fix the issue. In my canvasHelper.WebGL2ContextMock get method I was returning an already created mock object. So to fix the issue I create a new mock object each time it's called which seems to solve all my issues.

**Comment by florinn** [comment]
OK. Good to hear you fixed the issue.

**Comment by CodingMadeEasy** [comment]
Hi @florinn So I've continued my tests and the error seems to have sporadically. I can alleviate the issue by stopping and running the tests again but it's pretty annoying to say the least.

**Comment by CodingMadeEasy** [comment]
I think what would help is to have a clearer error message. Having an error message that says:

```
Error: function () {
                var args = [];
                for (var _i = 0; _i < arguments.length; _i++) {
                    args[_i] = arguments[_i];
                }
                _this._interceptor.removeInvocation(invocation);
                var method = new MethodInfo(target, p);
                var methodInvocation = new MethodInvocation(target, method, args, ProxyType.DYNAMIC);
                _this._interceptor.intercept(methodInvocation);
                return methodInvocation.returnValue;
            }: undefined
```

doesn't help much.

**Comment by florinn** [comment]
Could you create a jsbin/codepen with your failing test?

**Comment by florinn** [comment]
Let me know when you have the chance to create a repro project. Closing it for now.
