### ISSUE TITLE
Proxy polyfill does not support trap '_interceptor'

### ISSUE THREAD

**Issue by typedefJorge** [florinn/typemoq#73]
Hey there, Im really loving this library, trying to get sinon or testdouble to work well with typescript was super confusing. This literally took me 10 mins to setup. Anyways I digress: so im running tests in Chrome, FF, Edge, and IE in karma and im including { pattern: "node_modules/proxy-polyfill/proxy.min.js"}, so that es6 proxies are available globally. The issue is that IE is throwing an error in the proxy-polyfill code, here's the stack trace:
IE 11.0.0 (Windows 10 0.0.0) Triangle  constructor encountered a declaration exception FAILED
        TypeError: Proxy polyfill does not support trap '_interceptor'
           at c.a (node_modules/proxy-polyfill/proxy.min.js:1:429)
           at ProxyES6 (C:/Users/jnone/AppData/Local/Temp/karma-typescript-bundle-59484t8mBlTQV1wq.js:13353:9)
           at ProxyES6.of (C:/Users/jnone/AppData/Local/Temp/karma-typescript-bundle-59484t8mBlTQV1wq.js:13358:9)
           at ProxyFactory.createProxyES6 (C:/Users/jnone/AppData/Local/Temp/karma-typescript-bundle-59484t8mBlTQV1wq.js:13424:9)
           at DynamicMock (C:/Users/jnone/AppData/Local/Temp/karma-typescript-bundle-59484t8mBlTQV1wq.js:14043:9)
           at DynamicMock.ofType (C:/Users/jnone/AppData/Local/Temp/karma-typescript-bundle-59484t8mBlTQV1wq.js:14047:9)
           at MockApi.ofType (C:/Users/jnone/AppData/Local/Temp/karma-typescript-bundle-59484t8mBlTQV1wq.js:14086:13)
           at Anonymous function (spec/graphics/shapes2d/triangle.spec.js:10:9)

Im not sure if this is an issue here or with the proxy-polyfill library, or if this is something you guys could fix?

**Comment by dizel3d** [comment]
@typedefJorge, there is no working Proxy polyfill for IE, it's impossible technically.

**Comment by typedefJorge** [comment]
@dizel3d Thanks for the reply. proxy-polyfill claims to be working in IE9+, is that not true?

from their [readme](https://github.com/GoogleChrome/proxy-polyfill#supports):
Supports
The polyfill supports browsers that implement the full ES5 spec, such as IE9+ and Safari 6+. Firefox, Chrome, Safari 10+ and Edge support Proxy natively.

**Comment by florinn** [comment]
`proxy-polyfill` requires **the target to be known at creation time**. 
On the other hand, the ES6 Proxy is able to intercept property access as it happens without requiring prior knowledge. So ES6 Proxy can't get polyfilled as it has to be supported natively by browser/nodejs. 

For static mocking (known target at proxy creation time), `typemoq` uses a custom internal Proxy which is quite similar to `proxy-polyfill`.
For dynamic mocking (**unknown target** at proxy creation time), `typemoq` uses ES6 Proxy. So if you're using this feature make sure to run your tests in a browser/nodejs version that implements ES6 Proxy.

**Comment by typedefJorge** [comment]
oh alright, thanks for the response
